application: manugarg-articles
version: live-20121022
runtime: python
api_version: 1

handlers:
- url: /aboutelfauxiliaryvectors
  script: redirect2html.py

- url: /stack.txt
  script: redirect2html.py

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /(.*\.(pdf|ppt|txt|html))
  static_files: static/\1
  upload: static/(.*\.(pdf|ppt|txt|html))

